# Generated by Django 3.2.13 on 2024-10-11 11:50

from django.db import migrations, models
import etebase_server.django.models


class Migration(migrations.Migration):

    dependencies = [
        ("django_etebase", "0037_auto_20210127_1237"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitemchunk",
            name="content",
            field=models.BinaryField(blank=True, null=True, editable=True),
        ),
        migrations.AlterField(
            model_name="collectionitemchunk",
            name="chunkFile",
            field=models.FileField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                upload_to=etebase_server.django.models.chunk_directory_path,
            ),
        ),
    ]
