# Generated by Django 3.2.13 on 2024-10-14 07:42

from django.db import migrations, models
import etebase_server.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_etebase', '0038_auto_20241011_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitemchunk',
            name='chunkFile',
            field=models.FileField(blank=True, max_length=150, null=True, upload_to=etebase_server.django.models.chunk_directory_path),
        ),
    ]
